### ISSUE TITLE
Fix tests on Linux (testing on Ubuntu 20.04)

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/go-keyconfig#1]
**Describe the bug**
On Ubuntu 20.04:

```shell
$ go test -v ./...
# github.com/infamousjoeg/go-keyconfig
./config.go:14:20: undefined: keychain.GetGenericPasswordAccounts
./config.go:39:11: undefined: keychain.NewGenericPassword
./config.go:42:26: undefined: keychain.SynchronizableNo
./config.go:43:22: undefined: keychain.AccessibleAfterFirstUnlock
./config.go:45:9: undefined: keychain.AddItem
./config.go:50:12: undefined: keychain.ErrorDuplicateItem
./config.go:51:10: undefined: keychain.ErrorDuplicateItem
./config.go:66:11: undefined: keychain.NewItem
./config.go:67:20: undefined: keychain.SecClassGenericPassword
./config.go:70:22: undefined: keychain.MatchLimitOne
./config.go:70:22: too many errors
FAIL	github.com/infamousjoeg/go-keyconfig [build failed]
```

**To Reproduce**
See above command.

**Expected behavior**
Tests all pass successfully on MacOS Big Sur. Expected to pass on Linux, as well

**Comment by hanagantig** [comment]
Hi. Check the [keychain.go](https://github.com/keybase/go-keychain/blob/master/keychain.go) from the go-keychain package you use. There is build tags:
```go
//go:build darwin
// +build darwin
```
It means that the file keychain.go will be included only in macOS builds. Thats why your tests running in Ubuntu can't find the methods.

**Comment by infamousjoeg** [comment]
Note: This can be used for Windows Credential Manager - https://github.com/danieljoos/wincred

**Comment by infamousjoeg** [comment]
Note: This can be used for Linux DBUS keyring (gnome-keyring, ksecretservice) - https://github.com/keybase/go-keychain/blob/master/secretservice/secretservice.go
